// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7v5Gk-2Ta1Tv_LzCcfWMoU-IH4ULMRiI',
    appId: '1:581342125266:web:b0b36bb23993f5f14fa10b',
    messagingSenderId: '581342125266',
    projectId: 'jogak-jogak',
    authDomain: 'jogak-jogak.firebaseapp.com',
    storageBucket: 'jogak-jogak.firebasestorage.app',
    measurementId: 'G-8ZRGPFGMJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxyHuHsm59XwlHUWt_mxWwtsdVUQQq2E',
    appId: '1:581342125266:android:8cc765e5528a62a84fa10b',
    messagingSenderId: '581342125266',
    projectId: 'jogak-jogak',
    storageBucket: 'jogak-jogak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8mSx6p9nsUBBDkW8LRhrz87UIH86kCok',
    appId: '1:581342125266:ios:d473f624a61430f34fa10b',
    messagingSenderId: '581342125266',
    projectId: 'jogak-jogak',
    storageBucket: 'jogak-jogak.firebasestorage.app',
    iosBundleId: 'com.example.jogakJogak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8mSx6p9nsUBBDkW8LRhrz87UIH86kCok',
    appId: '1:581342125266:ios:d473f624a61430f34fa10b',
    messagingSenderId: '581342125266',
    projectId: 'jogak-jogak',
    storageBucket: 'jogak-jogak.firebasestorage.app',
    iosBundleId: 'com.example.jogakJogak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7v5Gk-2Ta1Tv_LzCcfWMoU-IH4ULMRiI',
    appId: '1:581342125266:web:7ff4891f928d9ae24fa10b',
    messagingSenderId: '581342125266',
    projectId: 'jogak-jogak',
    authDomain: 'jogak-jogak.firebaseapp.com',
    storageBucket: 'jogak-jogak.firebasestorage.app',
    measurementId: 'G-T5XQQPXHZB',
  );

}